service: search-service

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: python3.10

package:
  # exclude files from lambda deployment package
  patterns:
  - '!tests/**/*'
  - '!__pycache__/**/*'
  - '!.pytest_cache/**/*'
  - '!requirements*'
  - '!*.json'
  - '!node_modules/**/*'

custom:
  pythonRequirements:
    slim: true
    layer: true

functions:
  search:
    handler: handler.handler
    timeout: 60
    url: true
    environment:
      DB_HOST: ${env:DB_HOST}
      DB_PORT: ${env:DB_PORT}
      DB_DBNAME: ${env:DB_DBNAME}
      DB_USER: ${env:DB_USER}
      DB_PASSWORD: ${env:DB_PASSWORD}
    layers:
      - Ref: PythonRequirementsLambdaLayer

plugins:
  - serverless-python-requirements
